### ISSUE TITLE
Host name can't be resolved

### ISSUE THREAD

**Issue by BourzRoss** [d-torrance/wmforecast#6]
Dockapp is starting without error message. In dockapp itself - error pic and notify "Couldn't resolve host name". Nothing more. Restart, click on icon  not help

**Comment by d-torrance** [comment]
I'm getting the same behavior.  It's likely a change in Yahoo's API.  I'll try and figure out what's going on in the near future.

**Comment by d-torrance** [comment]
Yeah, Yahoo changed things around.  From https://developer.yahoo.com/weather/:

> Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired.

I'll try to get an updated version out in the next week or so.

**Comment by BourzRoss** [comment]
Thank! Happy New Year!))

**Comment by BourzRoss** [comment]
Is there any news about wmforecast?

**Comment by d-torrance** [comment]
My original "next week or so" guess was a little too optimistic!  I just need to find some time and figure out Yahoo's new API.  Hopefully this is in the near future...

Thanks for your patience!

**Comment by BourzRoss** [comment]
Thanks you!

**Comment by BourzRoss** [comment]
It die...RIP wmforecast....

**Comment by d-torrance** [comment]
Well, a week turned into over a year, but it's finally fixed!

Rather than dealing with Yahoo's API (which now requires a key), I switched everything over to [libgweather](https://wiki.gnome.org/Projects/LibGWeather).

I'd still like to do a few things before I make an official release (probably 1.0 since there are some pretty big changes), but you can view the weather again!
